// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * ArtifactRecord
 *
 * One named artifact produced by a stage, registered in the manifest.
 */
export type ArtifactRecord = {
    /**
     * Name
     */
    name: string;
    /**
     * Relpath
     *
     * Path relative to the run directory
     */
    relpath: string;
    /**
     * Schema Version
     */
    schema_version: number;
    /**
     * Producer
     *
     * Component/stage id + version that wrote it
     */
    producer: string;
    /**
     * Sha256
     */
    sha256?: string | null;
    /**
     * Row Count
     */
    row_count?: number | null;
};

/**
 * AuditRecordOut
 */
export type AuditRecordOut = {
    /**
     * Seq
     */
    seq: number;
    /**
     * Ts
     */
    ts: string;
    /**
     * Actor
     */
    actor: string;
    /**
     * Action
     */
    action: string;
    /**
     * Detail
     */
    detail: {
        [key: string]: unknown;
    };
    /**
     * Prev Hash
     */
    prev_hash: string;
    /**
     * Hash
     */
    hash: string;
};

/**
 * AuditVerifyOut
 */
export type AuditVerifyOut = {
    /**
     * Intact
     */
    intact: boolean;
    /**
     * First Broken Seq
     */
    first_broken_seq: number | null;
};

/**
 * CameraTimeBase
 *
 * Maps a camera's local frame index to scene-clock seconds.
 */
export type CameraTimeBase = {
    /**
     * Camera Id
     */
    camera_id: string;
    /**
     * Fps
     */
    fps: number;
    /**
     * Offset S
     *
     * scene_time = frame_index / fps + offset_s
     */
    offset_s?: number;
    /**
     * Drift S Per Hour
     *
     * Linear clock drift correction; 0 for short clips
     */
    drift_s_per_hour?: number;
    source?: TimeBaseSource;
    /**
     * Confidence
     */
    confidence?: number;
};

/**
 * CancelOut
 */
export type CancelOut = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * CheckpointRef
 *
 * Content-addressed weights file.
 */
export type CheckpointRef = {
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Filename
     */
    filename: string;
};

/**
 * ConfigLayer
 *
 * Config layers, listed lowest → highest precedence.
 */
export type ConfigLayer = 'profile_default' | 'deployment' | 'case' | 'run_override';

/**
 * EvalReportRef
 *
 * Reference to an evaluation-harness report backing a lifecycle change.
 */
export type EvalReportRef = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Benchmark
     */
    benchmark: string;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: number;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Job
 */
export type Job = {
    /**
     * Job Id
     */
    job_id?: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
    executor?: JobExecutor;
    status?: JobStatus;
    /**
     * Priority
     */
    priority?: number;
    /**
     * Run Id
     */
    run_id?: string | null;
    /**
     * Worker Id
     */
    worker_id?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Cancel Requested
     */
    cancel_requested?: boolean;
    /**
     * Attempt
     */
    attempt?: number;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Claimed At
     */
    claimed_at?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Heartbeat At
     */
    heartbeat_at?: string | null;
};

/**
 * JobExecutor
 *
 * Where a job runs (D13). Sensitive footage never leaves premises:
 * the executor is a property of the JOB, chosen at submit time.
 */
export type JobExecutor = 'local' | 'kaggle';

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'claimed' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * JobSubmitRequest
 */
export type JobSubmitRequest = {
    /**
     * Videos
     */
    videos?: {
        [key: string]: string;
    };
    /**
     * Profile
     */
    profile?: string;
    /**
     * Role
     */
    role?: 'gallery' | 'probe' | 'benchmark' | 'adaptation';
    /**
     * Fps
     */
    fps?: number | null;
    /**
     * Overrides
     */
    overrides?: Array<string>;
    /**
     * Resume Run Id
     */
    resume_run_id?: string | null;
    /**
     * Executor
     */
    executor?: 'local' | 'kaggle';
    /**
     * Priority
     */
    priority?: number;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ModelEntry
 */
export type ModelEntry = {
    /**
     * Model Id
     */
    model_id: string;
    task: ModelTask;
    /**
     * Architecture
     */
    architecture: string;
    checkpoint: CheckpointRef;
    stage?: ModelStage;
    /**
     * Trained On
     *
     * Dataset ids
     */
    trained_on?: Array<string>;
    /**
     * Adapted For Site
     *
     * Deployment/site id for adaptation outputs
     */
    adapted_for_site?: string | null;
    /**
     * Eval Reports
     */
    eval_reports?: Array<EvalReportRef>;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Notes
     */
    notes?: string;
};

/**
 * ModelStage
 */
export type ModelStage = 'candidate' | 'validated' | 'production' | 'retired';

/**
 * ModelTask
 */
export type ModelTask = 'detection' | 'multi_view_detection' | 'reid_vehicle' | 'reid_person' | 'reid_cc_person' | 'face' | 'gait';

/**
 * PromoteRequest
 */
export type PromoteRequest = {
    /**
     * To
     */
    to: 'validated' | 'production';
    /**
     * Eval Run Id
     */
    eval_run_id?: string | null;
    /**
     * Benchmark
     */
    benchmark?: string;
    /**
     * Metrics
     */
    metrics?: {
        [key: string]: number;
    };
    /**
     * Notes
     */
    notes?: string;
};

/**
 * ResolvedConfig
 *
 * The frozen effective configuration of one run.
 */
export type ResolvedConfig = {
    /**
     * Values
     *
     * Flat dot-keyed key → value
     */
    values: {
        [key: string]: unknown;
    };
    /**
     * Provenance
     *
     * key → the layer that supplied its final value
     */
    provenance: {
        [key: string]: ConfigLayer;
    };
    /**
     * Config Hash
     *
     * sha256 over canonical values JSON
     */
    config_hash: string;
};

/**
 * RollbackRequest
 */
export type RollbackRequest = {
    /**
     * Task
     */
    task: string;
};

/**
 * RunManifest
 *
 * Complete, self-describing record of one pipeline run.
 */
export type RunManifest = {
    /**
     * Schema Version
     */
    schema_version?: number;
    /**
     * Run Id
     */
    run_id: string;
    role: RunRole;
    status?: RunStatus;
    /**
     * Profile Name
     */
    profile_name: string;
    /**
     * Case Id
     */
    case_id?: string | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Created By
     *
     * Operator identity (audit)
     */
    created_by?: string | null;
    /**
     * Inputs
     */
    inputs?: Array<VideoInput>;
    timebase?: SceneClock;
    config?: ResolvedConfig | null;
    /**
     * Artifacts
     */
    artifacts?: {
        [key: string]: ArtifactRecord;
    };
    /**
     * Error
     */
    error?: string | null;
};

/**
 * RunRole
 */
export type RunRole = 'gallery' | 'probe' | 'benchmark' | 'adaptation';

/**
 * RunStatus
 */
export type RunStatus = 'created' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * RunSummary
 */
export type RunSummary = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Status
     */
    status: string;
    /**
     * Profile Name
     */
    profile_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Config Hash
     */
    config_hash: string | null;
    /**
     * Num Artifacts
     */
    num_artifacts: number;
    /**
     * Error
     */
    error: string | null;
};

/**
 * SceneClock
 *
 * The run-level collection of camera time bases.
 */
export type SceneClock = {
    /**
     * Cameras
     */
    cameras?: {
        [key: string]: CameraTimeBase;
    };
};

/**
 * SearchHitOut
 */
export type SearchHitOut = {
    /**
     * Probe Camera Id
     */
    probe_camera_id: string;
    /**
     * Probe Track Id
     */
    probe_track_id: number;
    /**
     * Gallery Camera Id
     */
    gallery_camera_id: string;
    /**
     * Gallery Track Id
     */
    gallery_track_id: number;
    /**
     * Stream
     */
    stream: string;
    /**
     * Score
     */
    score: number;
    /**
     * Probability
     *
     * Calibrated P(same identity); null when the stream has no calibration artifact (we never invent probabilities)
     */
    probability?: number | null;
    /**
     * Gallery Entity Class
     */
    gallery_entity_class: string;
    /**
     * Gallery Start Ts S
     */
    gallery_start_ts_s: number;
    /**
     * Gallery End Ts S
     */
    gallery_end_ts_s: number;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Gallery Run Id
     */
    gallery_run_id: string;
    /**
     * Probe Run Id
     */
    probe_run_id: string;
    /**
     * Stream
     */
    stream?: string | null;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Min Score
     */
    min_score?: number;
};

/**
 * SearchResponse
 */
export type SearchResponse = {
    /**
     * Gallery Run Id
     */
    gallery_run_id: string;
    /**
     * Probe Run Id
     */
    probe_run_id: string;
    /**
     * Stream
     */
    stream: string;
    /**
     * Calibrated
     */
    calibrated: boolean;
    /**
     * Hits
     */
    hits: Array<SearchHitOut>;
};

/**
 * TimeBaseSource
 */
export type TimeBaseSource = 'assumed' | 'manual' | 'timestamp_ocr' | 'event_alignment' | 'synchronized';

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VideoInput
 *
 * One source evidence video, hashed at ingest (chain of custody).
 */
export type VideoInput = {
    /**
     * Camera Id
     */
    camera_id: string;
    /**
     * Original Path
     */
    original_path: string;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Duration S
     */
    duration_s?: number | null;
    /**
     * Fps
     */
    fps?: number | null;
    /**
     * Width
     */
    width?: number | null;
    /**
     * Height
     */
    height?: number | null;
    /**
     * Normalized Artifact
     *
     * Artifact name of the canonical transcoded copy, if any
     */
    normalized_artifact?: string | null;
    /**
     * Transforms
     *
     * Ordered ingest transforms applied (e.g. 'transcode:h264', 'dewarp:fisheye')
     */
    transforms?: Array<string>;
};

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type MeAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type MeAuthMeGetResponse = MeAuthMeGetResponses[keyof MeAuthMeGetResponses];

export type ListRunsRunsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Role
         */
        role?: string | null;
    };
    url: '/runs';
};

export type ListRunsRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRunsRunsGetError = ListRunsRunsGetErrors[keyof ListRunsRunsGetErrors];

export type ListRunsRunsGetResponses = {
    /**
     * Response List Runs Runs Get
     *
     * Successful Response
     */
    200: Array<RunSummary>;
};

export type ListRunsRunsGetResponse = ListRunsRunsGetResponses[keyof ListRunsRunsGetResponses];

export type GetRunRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}';
};

export type GetRunRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunRunsRunIdGetError = GetRunRunsRunIdGetErrors[keyof GetRunRunsRunIdGetErrors];

export type GetRunRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunManifest;
};

export type GetRunRunsRunIdGetResponse = GetRunRunsRunIdGetResponses[keyof GetRunRunsRunIdGetResponses];

export type ListEventsRunsRunIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/runs/{run_id}/events';
};

export type ListEventsRunsRunIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsRunsRunIdEventsGetError = ListEventsRunsRunIdEventsGetErrors[keyof ListEventsRunsRunIdEventsGetErrors];

export type ListEventsRunsRunIdEventsGetResponses = {
    /**
     * Response List Events Runs  Run Id  Events Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListEventsRunsRunIdEventsGetResponse = ListEventsRunsRunIdEventsGetResponses[keyof ListEventsRunsRunIdEventsGetResponses];

export type StreamEventsRunsRunIdEventsStreamGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}/events/stream';
};

export type StreamEventsRunsRunIdEventsStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamEventsRunsRunIdEventsStreamGetError = StreamEventsRunsRunIdEventsStreamGetErrors[keyof StreamEventsRunsRunIdEventsStreamGetErrors];

export type StreamEventsRunsRunIdEventsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetReportRunsRunIdReportGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}/report';
};

export type GetReportRunsRunIdReportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportRunsRunIdReportGetError = GetReportRunsRunIdReportGetErrors[keyof GetReportRunsRunIdReportGetErrors];

export type GetReportRunsRunIdReportGetResponses = {
    /**
     * Response Get Report Runs  Run Id  Report Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetReportRunsRunIdReportGetResponse = GetReportRunsRunIdReportGetResponses[keyof GetReportRunsRunIdReportGetResponses];

export type DownloadArtifactRunsRunIdArtifactsNameGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/runs/{run_id}/artifacts/{name}';
};

export type DownloadArtifactRunsRunIdArtifactsNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadArtifactRunsRunIdArtifactsNameGetError = DownloadArtifactRunsRunIdArtifactsNameGetErrors[keyof DownloadArtifactRunsRunIdArtifactsNameGetErrors];

export type DownloadArtifactRunsRunIdArtifactsNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListJobsJobsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Job Status
         */
        job_status?: string | null;
    };
    url: '/jobs';
};

export type ListJobsJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsJobsGetError = ListJobsJobsGetErrors[keyof ListJobsJobsGetErrors];

export type ListJobsJobsGetResponses = {
    /**
     * Response List Jobs Jobs Get
     *
     * Successful Response
     */
    200: Array<Job>;
};

export type ListJobsJobsGetResponse = ListJobsJobsGetResponses[keyof ListJobsJobsGetResponses];

export type SubmitJobJobsPostData = {
    body: JobSubmitRequest;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type SubmitJobJobsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitJobJobsPostError = SubmitJobJobsPostErrors[keyof SubmitJobJobsPostErrors];

export type SubmitJobJobsPostResponses = {
    /**
     * Successful Response
     */
    202: Job;
};

export type SubmitJobJobsPostResponse = SubmitJobJobsPostResponses[keyof SubmitJobJobsPostResponses];

export type GetJobJobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type GetJobJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobJobsJobIdGetError = GetJobJobsJobIdGetErrors[keyof GetJobJobsJobIdGetErrors];

export type GetJobJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: Job;
};

export type GetJobJobsJobIdGetResponse = GetJobJobsJobIdGetResponses[keyof GetJobJobsJobIdGetResponses];

export type CancelJobJobsJobIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/cancel';
};

export type CancelJobJobsJobIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelJobJobsJobIdCancelPostError = CancelJobJobsJobIdCancelPostErrors[keyof CancelJobJobsJobIdCancelPostErrors];

export type CancelJobJobsJobIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: CancelOut;
};

export type CancelJobJobsJobIdCancelPostResponse = CancelJobJobsJobIdCancelPostResponses[keyof CancelJobJobsJobIdCancelPostResponses];

export type StreamJobEventsJobsJobIdEventsStreamGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/events/stream';
};

export type StreamJobEventsJobsJobIdEventsStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamJobEventsJobsJobIdEventsStreamGetError = StreamJobEventsJobsJobIdEventsStreamGetErrors[keyof StreamJobEventsJobsJobIdEventsStreamGetErrors];

export type StreamJobEventsJobsJobIdEventsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListModelsModelsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Task
         */
        task?: string | null;
        /**
         * Stage
         */
        stage?: string | null;
    };
    url: '/models';
};

export type ListModelsModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelsModelsGetError = ListModelsModelsGetErrors[keyof ListModelsModelsGetErrors];

export type ListModelsModelsGetResponses = {
    /**
     * Response List Models Models Get
     *
     * Successful Response
     */
    200: Array<ModelEntry>;
};

export type ListModelsModelsGetResponse = ListModelsModelsGetResponses[keyof ListModelsModelsGetResponses];

export type GetModelModelsModelIdGetData = {
    body?: never;
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/models/{model_id}';
};

export type GetModelModelsModelIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelModelsModelIdGetError = GetModelModelsModelIdGetErrors[keyof GetModelModelsModelIdGetErrors];

export type GetModelModelsModelIdGetResponses = {
    /**
     * Successful Response
     */
    200: ModelEntry;
};

export type GetModelModelsModelIdGetResponse = GetModelModelsModelIdGetResponses[keyof GetModelModelsModelIdGetResponses];

export type ModelHistoryModelsModelIdHistoryGetData = {
    body?: never;
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/models/{model_id}/history';
};

export type ModelHistoryModelsModelIdHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModelHistoryModelsModelIdHistoryGetError = ModelHistoryModelsModelIdHistoryGetErrors[keyof ModelHistoryModelsModelIdHistoryGetErrors];

export type ModelHistoryModelsModelIdHistoryGetResponses = {
    /**
     * Response Model History Models  Model Id  History Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ModelHistoryModelsModelIdHistoryGetResponse = ModelHistoryModelsModelIdHistoryGetResponses[keyof ModelHistoryModelsModelIdHistoryGetResponses];

export type PromoteModelModelsModelIdPromotePostData = {
    body: PromoteRequest;
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/models/{model_id}/promote';
};

export type PromoteModelModelsModelIdPromotePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PromoteModelModelsModelIdPromotePostError = PromoteModelModelsModelIdPromotePostErrors[keyof PromoteModelModelsModelIdPromotePostErrors];

export type PromoteModelModelsModelIdPromotePostResponses = {
    /**
     * Successful Response
     */
    200: ModelEntry;
};

export type PromoteModelModelsModelIdPromotePostResponse = PromoteModelModelsModelIdPromotePostResponses[keyof PromoteModelModelsModelIdPromotePostResponses];

export type RetireModelModelsModelIdRetirePostData = {
    body?: never;
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/models/{model_id}/retire';
};

export type RetireModelModelsModelIdRetirePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetireModelModelsModelIdRetirePostError = RetireModelModelsModelIdRetirePostErrors[keyof RetireModelModelsModelIdRetirePostErrors];

export type RetireModelModelsModelIdRetirePostResponses = {
    /**
     * Successful Response
     */
    200: ModelEntry;
};

export type RetireModelModelsModelIdRetirePostResponse = RetireModelModelsModelIdRetirePostResponses[keyof RetireModelModelsModelIdRetirePostResponses];

export type RollbackProductionModelsRollbackPostData = {
    body: RollbackRequest;
    path?: never;
    query?: never;
    url: '/models/rollback';
};

export type RollbackProductionModelsRollbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RollbackProductionModelsRollbackPostError = RollbackProductionModelsRollbackPostErrors[keyof RollbackProductionModelsRollbackPostErrors];

export type RollbackProductionModelsRollbackPostResponses = {
    /**
     * Successful Response
     */
    200: ModelEntry;
};

export type RollbackProductionModelsRollbackPostResponse = RollbackProductionModelsRollbackPostResponses[keyof RollbackProductionModelsRollbackPostResponses];

export type SearchSearchPostData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/search';
};

export type SearchSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSearchPostError = SearchSearchPostErrors[keyof SearchSearchPostErrors];

export type SearchSearchPostResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchSearchPostResponse = SearchSearchPostResponses[keyof SearchSearchPostResponses];

export type ListAuditAuditGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/audit';
};

export type ListAuditAuditGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAuditAuditGetError = ListAuditAuditGetErrors[keyof ListAuditAuditGetErrors];

export type ListAuditAuditGetResponses = {
    /**
     * Response List Audit Audit Get
     *
     * Successful Response
     */
    200: Array<AuditRecordOut>;
};

export type ListAuditAuditGetResponse = ListAuditAuditGetResponses[keyof ListAuditAuditGetResponses];

export type VerifyAuditVerifyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/audit/verify';
};

export type VerifyAuditVerifyGetResponses = {
    /**
     * Successful Response
     */
    200: AuditVerifyOut;
};

export type VerifyAuditVerifyGetResponse = VerifyAuditVerifyGetResponses[keyof VerifyAuditVerifyGetResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
