"""v75: Consolidate ALL optimal parameters + scan untested features.

CRITICAL FINDING: Cell 9/12 had stale v46 defaults. Parameters found optimal
in v67-v73 sweeps were NEVER consolidated into the single-run config:
  - AQE_K=2 → 3 (+0.9pp, v62)
  - algorithm=CC → conflict_free_cc (+0.21pp, v67)
  - appearance_weight=0.75 → 0.70 (+0.76pp, v73)
  - camera_bias=True → False (hurt -0.4pp, v54-57)
  - zone_model=True → False (hurt -0.4pp, v54-57)
  - intra_merge_thresh=0.75 → 0.80 (+0.14pp, v72)
  - intra_merge_gap=60 → 30 (v72)
  - fic.regularisation=3.0 → 0.1 (+0.08pp, v70)
  - cross_id_nms_iou=0.35 → 0.40 (+0.02pp, v68)
  - min_trajectory_frames=10 → 40 (v71)

Scan tests genuinely untried parameters:
  - Temporal overlap bonus: [0.0, 0.05, 0.10, 0.15, 0.20] (never swept)
  - Temporal overlap max_mean_time: [5.0, 10.0, 15.0]
  - AQE_K higher: [5, 7, 10] (only 2,3,4 tested)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NB = ROOT / "notebooks/kaggle/10c_stages45/mtmc-10c-stages-4-5-association-eval.ipynb"


def update_notebook():
    nb = json.load(open(NB, encoding="utf-8"))

    # ─── Cell 9 (index 9): Update constants to consolidated optimal ───
    cell9 = nb["cells"][9]
    new_c9 = [
        "# ---- Stage 4: Cross-camera association -------------------------------------\n",
        "# v75: CONSOLIDATED OPTIMAL — all params from v62-v73 sweeps\n",
        "AQE_K             = 3     # v62: 3 optimal (+0.9pp over 2)\n",
        "SIM_THRESH        = 0.53  # v58,v63,v70: confirmed optimal\n",
        "ALGORITHM         = \"conflict_free_cc\"  # v67: +0.21pp over CC\n",
        "LOUVAIN_RES       = 0.70  # fallback (unused with cfcc)\n",
        "\n",
        "# Weights — v73: appearance-heavy for vehicles\n",
        "APPEARANCE_WEIGHT = 0.70  # v73: +0.76pp over 0.75\n",
        "HSV_WEIGHT        = 0.0   # v46: disabled (hurts vehicles)\n",
        "ST_WEIGHT         = round(1.0 - APPEARANCE_WEIGHT - HSV_WEIGHT, 4)\n",
        "\n",
        "# Bridge pruning: v46 found pruning HURTS (-1.4pp) → disabled\n",
        "BRIDGE_PRUNE      = 0.0\n",
        "MAX_COMP_SIZE     = 12\n",
        "\n",
        "# Intra-camera merge (ReID-based): v72 optimal\n",
        "INTRA_MERGE       = True\n",
        "INTRA_MERGE_THRESH = 0.80  # v72: +0.14pp over 0.75\n",
        "INTRA_MERGE_GAP   = 30     # v72: gap-insensitive at 0.80\n",
        "\n",
        "# Score-level fusion with OSNet secondary embeddings\n",
        "FUSION_WEIGHT     = 0.10   # v53: 10% secondary (optimal)\n",
        "\n",
        "# v54-v57: camera_bias + zone_model BOTH HURT → disabled\n",
        "CAMERA_BIAS       = False\n",
        "CAMERA_BIAS_ITERS = 2\n",
        "ZONE_MODEL        = False\n",
        "ZONE_BONUS        = 0.06\n",
        "ZONE_PENALTY      = 0.04\n",
        "# Hierarchical: DISABLED (v54-56,v62: -1.0 to -5.1pp)\n",
        "HIERARCHICAL      = False\n",
        "HIER_CENTROID_TH  = 0.45\n",
        "HIER_MERGE_TH     = 0.45\n",
        "HIER_ORPHAN_TH    = 0.40\n",
        "\n",
        "# ---- Stage 5: Evaluation ----------------------------------------------------\n",
        "MTMC_ONLY = False\n",
        "\n",
        "print(\"Stage 4 params (v75 consolidated optimal):\")\n",
        "print(f\"  aqe_k={AQE_K}  sim_thresh={SIM_THRESH}  algorithm={ALGORITHM}  appearance_weight={APPEARANCE_WEIGHT}\")\n",
        "print(f\"  hsv_weight={HSV_WEIGHT}  st_weight={ST_WEIGHT}  bridge_prune={BRIDGE_PRUNE}  max_comp_size={MAX_COMP_SIZE}\")\n",
        "print(f\"  intra_merge={INTRA_MERGE}  intra_thresh={INTRA_MERGE_THRESH}  intra_gap={INTRA_MERGE_GAP}\")\n",
        "print(f\"  fusion_weight={FUSION_WEIGHT}\")\n",
        "print(f\"  camera_bias={CAMERA_BIAS}  zone_model={ZONE_MODEL}  hierarchical={HIERARCHICAL}\")\n",
        "print(f\"Stage 5: mtmc_only_submission={MTMC_ONLY}, stationary_filter=True\")\n",
    ]
    cell9["source"] = new_c9

    # ─── Cell 12 (index 12): Update run command with optimal overrides ───
    cell12 = nb["cells"][12]
    new_c12 = [
        "os.chdir(str(PROJECT))\n",
        "cmd = [\n",
        "    sys.executable, \"scripts/run_pipeline.py\",\n",
        "    \"--config\", \"configs/default.yaml\",\n",
        "    \"--dataset-config\", \"configs/datasets/cityflowv2.yaml\",\n",
        "    \"--stages\", \"4,5\",\n",
        "    \"--override\", f\"project.run_name={RUN_NAME}\",\n",
        "    \"--override\", f\"project.output_dir={DATA_OUT}\",\n",
        "    # Stage 4: Association (v75 consolidated optimal)\n",
        "    \"--override\", f\"stage4.association.query_expansion.k={AQE_K}\",\n",
        "    \"--override\", \"stage4.association.query_expansion.alpha=5.0\",\n",
        "    \"--override\", f\"stage4.association.graph.similarity_threshold={SIM_THRESH}\",\n",
        "    \"--override\", f\"stage4.association.graph.algorithm={ALGORITHM}\",\n",
        "    \"--override\", f\"stage4.association.graph.louvain_resolution={LOUVAIN_RES}\",\n",
        "    \"--override\", f\"stage4.association.graph.bridge_prune_margin={BRIDGE_PRUNE}\",\n",
        "    \"--override\", f\"stage4.association.graph.max_component_size={MAX_COMP_SIZE}\",\n",
        "    \"--override\", f\"stage4.association.weights.vehicle.appearance={APPEARANCE_WEIGHT}\",\n",
        "    \"--override\", f\"stage4.association.weights.vehicle.hsv={HSV_WEIGHT}\",\n",
        "    \"--override\", f\"stage4.association.weights.vehicle.spatiotemporal={ST_WEIGHT}\",\n",
        "    \"--override\", \"stage4.association.mutual_nn.top_k_per_query=20\",\n",
        "    \"--override\", \"stage4.association.fic.enabled=true\",\n",
        "    \"--override\", \"stage4.association.fic.regularisation=0.1\",\n",
        "    \"--override\", \"stage4.association.fac.enabled=false\",\n",
        "    # Score-level fusion with OSNet secondary embeddings\n",
        "    \"--override\", f\"stage4.association.secondary_embeddings.path={RUN_DIR}/stage2/embeddings_secondary.npy\",\n",
        "    \"--override\", f\"stage4.association.secondary_embeddings.weight={FUSION_WEIGHT}\",\n",
        "    # Camera bias + zone model: DISABLED (v54-57: both hurt)\n",
        "    \"--override\", f\"stage4.association.camera_bias.enabled={str(CAMERA_BIAS).lower()}\",\n",
        "    \"--override\", f\"stage4.association.camera_bias.iterations={CAMERA_BIAS_ITERS}\",\n",
        "    \"--override\", f\"stage4.association.zone_model.enabled={str(ZONE_MODEL).lower()}\",\n",
        "    \"--override\", \"stage4.association.zone_model.zone_data_path=configs/datasets/cityflowv2_zones.json\",\n",
        "    \"--override\", f\"stage4.association.zone_model.bonus={ZONE_BONUS}\",\n",
        "    \"--override\", f\"stage4.association.zone_model.penalty={ZONE_PENALTY}\",\n",
        "    # Hierarchical: DISABLED (v54-56,v62: hurt -1.0 to -5.1pp)\n",
        "    \"--override\", f\"stage4.association.hierarchical.enabled={str(HIERARCHICAL).lower()}\",\n",
        "    \"--override\", f\"stage4.association.hierarchical.centroid_threshold={HIER_CENTROID_TH}\",\n",
        "    \"--override\", f\"stage4.association.hierarchical.merge_threshold={HIER_MERGE_TH}\",\n",
        "    \"--override\", f\"stage4.association.hierarchical.orphan_threshold={HIER_ORPHAN_TH}\",\n",
        "    \"--override\", \"stage4.association.hierarchical.max_merge_size=12\",\n",
        "    # Intra-camera merge (ReID-based): v72 optimal\n",
        "    \"--override\", f\"stage4.association.intra_camera_merge.enabled={str(INTRA_MERGE).lower()}\",\n",
        "    \"--override\", f\"stage4.association.intra_camera_merge.threshold={INTRA_MERGE_THRESH}\",\n",
        "    \"--override\", f\"stage4.association.intra_camera_merge.max_time_gap={INTRA_MERGE_GAP}\",\n",
        "    # Stage 5: Post-processing (v68-71 optimal)\n",
        "    \"--override\", f\"stage5.mtmc_only_submission={str(MTMC_ONLY).lower()}\",\n",
        "    \"--override\", \"stage5.stationary_filter.enabled=true\",\n",
        "    \"--override\", \"stage5.stationary_filter.min_displacement_px=150\",\n",
        "    \"--override\", \"stage5.stationary_filter.max_mean_velocity_px=2.0\",\n",
        "    \"--override\", \"stage5.min_submission_confidence=0.15\",\n",
        "    \"--override\", \"stage5.cross_id_nms_iou=0.40\",\n",
        "    \"--override\", \"stage5.min_trajectory_confidence=0.30\",\n",
        "    \"--override\", \"stage5.min_trajectory_frames=40\",\n",
        "    \"--override\", \"stage5.track_edge_trim.enabled=false\",\n",
        "    \"--override\", \"stage5.track_smoothing.enabled=false\",\n",
        "    \"--override\", \"stage5.gt_frame_clip=true\",\n",
        "    \"--override\", \"stage5.gt_zone_filter=true\",\n",
        "]\n",
        "if GT_DIR:\n",
        "    cmd += [\"--override\", f\"stage5.ground_truth_dir={GT_DIR}\"]\n",
        "else:\n",
        "    print(\"WARNING: GT_DIR is empty — eval will skip metric computation\")\n",
        "print(\"CMD:\", \" \".join(str(c) for c in cmd))\n",
        "print(\"=\" * 70)\n",
        "t0 = time.time()\n",
        "r = subprocess.run(cmd, cwd=str(PROJECT))\n",
        "print(\"=\" * 70)\n",
        "elapsed = time.time() - t0\n",
        "if r.returncode != 0:\n",
        "    print(f\"\\u2717 FAILED after {elapsed/60:.1f} min\"); sys.exit(r.returncode)\n",
        "print(f\"\\u2713 Stages 4-5 done in {elapsed/60:.1f} min\")\n",
    ]
    cell12["source"] = new_c12

    # ─── Cell 15 (index 15): New scan — temporal overlap + AQE_K sweep ───
    cell15 = nb["cells"][15]
    new_c15 = [
        "# ============================================================\n",
        "# v75: Consolidated baseline + untested parameter scan\n",
        "#\n",
        "# CRITICAL: Cell 9/12 now have ALL optimal params from v62-v73.\n",
        "# The single run above IS the consolidated baseline.\n",
        "# This scan tests parameters NEVER previously swept:\n",
        "#   A) temporal_overlap.bonus (enabled by default, values never varied)\n",
        "#   B) temporal_overlap.max_mean_time (never varied)\n",
        "#   C) AQE_K=5,7,10 (only 2,3,4 tested before)\n",
        "# ============================================================\n",
        "SCAN_ENABLED = True\n",
        "\n",
        "if SCAN_ENABLED:\n",
        "    import itertools\n",
        "\n",
        "    # Individual configs (not full grid — targeted tests)\n",
        "    scan_configs = [\n",
        "        # 0: Baseline — consolidated optimal (same as single run)\n",
        "        {\"label\": \"baseline\"},\n",
        "        # --- Group A: Temporal Overlap Bonus (default: enabled, bonus=0.05, max_mean_time=5.0) ---\n",
        "        {\"label\": \"to_off\",     \"to_enabled\": False},\n",
        "        {\"label\": \"to_b002\",    \"to_bonus\": 0.02},\n",
        "        {\"label\": \"to_b010\",    \"to_bonus\": 0.10},\n",
        "        {\"label\": \"to_b015\",    \"to_bonus\": 0.15},\n",
        "        {\"label\": \"to_b020\",    \"to_bonus\": 0.20},\n",
        "        {\"label\": \"to_t10\",     \"to_max_time\": 10.0},\n",
        "        {\"label\": \"to_t15\",     \"to_max_time\": 15.0},\n",
        "        {\"label\": \"to_b010_t10\", \"to_bonus\": 0.10, \"to_max_time\": 10.0},\n",
        "        # --- Group B: AQE K higher values (only 2,3,4 tested) ---\n",
        "        {\"label\": \"aqe_k5\",     \"aqe_k\": 5},\n",
        "        {\"label\": \"aqe_k7\",     \"aqe_k\": 7},\n",
        "        {\"label\": \"aqe_k10\",    \"aqe_k\": 10},\n",
        "        # --- Group C: Combos ---\n",
        "        {\"label\": \"to_b010_k5\", \"to_bonus\": 0.10, \"aqe_k\": 5},\n",
        "    ]\n",
        "\n",
        "    print(f\"v75 scan: {len(scan_configs)} configs\")\n",
        "    print(\"=\" * 80)\n",
        "\n",
        "    results = []\n",
        "    for cfg in scan_configs:\n",
        "        label = cfg[\"label\"]\n",
        "        scan_run = f\"scan_{label}\"\n",
        "\n",
        "        # Resolve per-config overrides (defaults = consolidated optimal)\n",
        "        aqe_k = cfg.get(\"aqe_k\", AQE_K)\n",
        "        to_enabled = cfg.get(\"to_enabled\", True)\n",
        "        to_bonus = cfg.get(\"to_bonus\", 0.05)\n",
        "        to_max_time = cfg.get(\"to_max_time\", 5.0)\n",
        "\n",
        "        # Symlink stage1/2/3 from baseline run\n",
        "        scan_dir = DATA_OUT / scan_run\n",
        "        scan_dir.mkdir(parents=True, exist_ok=True)\n",
        "        for stage_sub in (\"stage1\", \"stage2\", \"stage3\"):\n",
        "            src = DATA_OUT / RUN_NAME / stage_sub\n",
        "            dst = scan_dir / stage_sub\n",
        "            if src.exists() and not dst.exists():\n",
        "                dst.symlink_to(src)\n",
        "\n",
        "        cmd_scan = [\n",
        "            sys.executable, \"scripts/run_pipeline.py\",\n",
        "            \"--config\", \"configs/default.yaml\",\n",
        "            \"--dataset-config\", \"configs/datasets/cityflowv2.yaml\",\n",
        "            \"--stages\", \"4,5\",\n",
        "            \"--override\", f\"project.run_name={scan_run}\",\n",
        "            \"--override\", f\"project.output_dir={DATA_OUT}\",\n",
        "            # v75: ALL consolidated optimal params\n",
        "            \"--override\", f\"stage4.association.query_expansion.k={aqe_k}\",\n",
        "            \"--override\", \"stage4.association.query_expansion.alpha=5.0\",\n",
        "            \"--override\", f\"stage4.association.graph.similarity_threshold={SIM_THRESH}\",\n",
        "            \"--override\", f\"stage4.association.graph.algorithm={ALGORITHM}\",\n",
        "            \"--override\", f\"stage4.association.graph.bridge_prune_margin={BRIDGE_PRUNE}\",\n",
        "            \"--override\", f\"stage4.association.graph.max_component_size={MAX_COMP_SIZE}\",\n",
        "            \"--override\", f\"stage4.association.weights.vehicle.appearance={APPEARANCE_WEIGHT}\",\n",
        "            \"--override\", f\"stage4.association.weights.vehicle.hsv={HSV_WEIGHT}\",\n",
        "            \"--override\", f\"stage4.association.weights.vehicle.spatiotemporal={ST_WEIGHT}\",\n",
        "            \"--override\", \"stage4.association.mutual_nn.top_k_per_query=20\",\n",
        "            \"--override\", \"stage4.association.fic.enabled=true\",\n",
        "            \"--override\", \"stage4.association.fic.regularisation=0.1\",\n",
        "            \"--override\", \"stage4.association.fac.enabled=false\",\n",
        "            \"--override\", f\"stage4.association.secondary_embeddings.path={RUN_DIR}/stage2/embeddings_secondary.npy\",\n",
        "            \"--override\", f\"stage4.association.secondary_embeddings.weight={FUSION_WEIGHT}\",\n",
        "            \"--override\", f\"stage4.association.camera_bias.enabled={str(CAMERA_BIAS).lower()}\",\n",
        "            \"--override\", f\"stage4.association.zone_model.enabled={str(ZONE_MODEL).lower()}\",\n",
        "            \"--override\", f\"stage4.association.hierarchical.enabled={str(HIERARCHICAL).lower()}\",\n",
        "            \"--override\", f\"stage4.association.intra_camera_merge.enabled={str(INTRA_MERGE).lower()}\",\n",
        "            \"--override\", f\"stage4.association.intra_camera_merge.threshold={INTRA_MERGE_THRESH}\",\n",
        "            \"--override\", f\"stage4.association.intra_camera_merge.max_time_gap={INTRA_MERGE_GAP}\",\n",
        "            # Temporal overlap (the variable being tested)\n",
        "            \"--override\", f\"stage4.association.temporal_overlap.enabled={str(to_enabled).lower()}\",\n",
        "            \"--override\", f\"stage4.association.temporal_overlap.bonus={to_bonus}\",\n",
        "            \"--override\", f\"stage4.association.temporal_overlap.max_mean_time={to_max_time}\",\n",
        "            # Stage 5: v68-71 optimal\n",
        "            \"--override\", f\"stage5.mtmc_only_submission={str(MTMC_ONLY).lower()}\",\n",
        "            \"--override\", \"stage5.stationary_filter.enabled=true\",\n",
        "            \"--override\", \"stage5.stationary_filter.min_displacement_px=150\",\n",
        "            \"--override\", \"stage5.stationary_filter.max_mean_velocity_px=2.0\",\n",
        "            \"--override\", \"stage5.min_submission_confidence=0.15\",\n",
        "            \"--override\", \"stage5.cross_id_nms_iou=0.40\",\n",
        "            \"--override\", \"stage5.min_trajectory_confidence=0.30\",\n",
        "            \"--override\", \"stage5.min_trajectory_frames=40\",\n",
        "            \"--override\", \"stage5.track_edge_trim.enabled=false\",\n",
        "            \"--override\", \"stage5.track_smoothing.enabled=false\",\n",
        "            \"--override\", \"stage5.gt_frame_clip=true\",\n",
        "            \"--override\", \"stage5.gt_zone_filter=true\",\n",
        "        ]\n",
        "        if GT_DIR:\n",
        "            cmd_scan += [\"--override\", f\"stage5.ground_truth_dir={GT_DIR}\"]\n",
        "\n",
        "        t0 = time.time()\n",
        "        r = subprocess.run(cmd_scan, cwd=str(PROJECT), capture_output=True)\n",
        "        elapsed = time.time() - t0\n",
        "\n",
        "        # Read metrics\n",
        "        report = DATA_OUT / scan_run / \"stage5\" / \"evaluation_report.json\"\n",
        "        idf1 = mtmc_idf1 = mota = hota = mtmc_mota = 0.0\n",
        "        if report.exists():\n",
        "            rp = json.loads(report.read_text())\n",
        "            m = rp.get(\"metrics\", rp)\n",
        "            idf1 = m.get(\"idf1\", m.get(\"IDF1\", 0.0))\n",
        "            mtmc_idf1 = m.get(\"mtmc_idf1\", 0.0)\n",
        "            mota = m.get(\"MOTA\", m.get(\"mota\", 0.0))\n",
        "            hota = m.get(\"HOTA\", m.get(\"hota\", 0.0))\n",
        "            details = rp.get(\"details\", {})\n",
        "            mtmc_mota = details.get(\"mtmc_mota\", mota)\n",
        "\n",
        "        results.append({\n",
        "            \"label\": label,\n",
        "            \"aqe_k\": aqe_k,\n",
        "            \"to_enabled\": to_enabled,\n",
        "            \"to_bonus\": to_bonus,\n",
        "            \"to_max_time\": to_max_time,\n",
        "            \"idf1\": idf1,\n",
        "            \"mtmc_idf1\": mtmc_idf1,\n",
        "            \"MOTA\": mota,\n",
        "            \"MTMC_MOTA\": mtmc_mota,\n",
        "            \"HOTA\": hota,\n",
        "            \"time\": elapsed,\n",
        "        })\n",
        "        status = \"OK\" if r.returncode == 0 else \"FAIL\"\n",
        "        print(f\"  [{status}] {label:20s} aqe_k={aqe_k} to={to_enabled}/{to_bonus}/{to_max_time} \"\n",
        "              f\"-> idf1={idf1:.4f} mtmc_idf1={mtmc_idf1:.4f} HOTA={hota:.4f} ({elapsed/60:.1f}m)\")\n",
        "\n",
        "    # Sort by mtmc_idf1\n",
        "    results.sort(key=lambda x: x[\"mtmc_idf1\"], reverse=True)\n",
        "    print(\"\\n\" + \"=\" * 80)\n",
        "    print(\"v75 SCAN RESULTS (sorted by mtmc_idf1)\")\n",
        "    print(\"=\" * 80)\n",
        "    print(f\"{'label':<22} {'k':>3} {'to_on':>5} {'bonus':>6} {'max_t':>6} {'idf1':>7} {'mtmc':>7} {'HOTA':>7}\")\n",
        "    for r2 in results:\n",
        "        print(f\"{r2['label']:<22} {r2['aqe_k']:>3} {str(r2['to_enabled']):>5} {r2['to_bonus']:>6.2f} \"\n",
        "              f\"{r2['to_max_time']:>6.1f} {r2['idf1']:>7.4f} {r2['mtmc_idf1']:>7.4f} {r2['HOTA']:>7.4f}\")\n",
        "    best = results[0]\n",
        "    print(f\"\\nBEST: {best['label']} -> mtmc_idf1={best['mtmc_idf1']:.4f} idf1={best['idf1']:.4f}\")\n",
        "\n",
        "    # --- Parameter sensitivity ---\n",
        "    print(\"\\n\" + \"=\" * 80)\n",
        "    print(\"PARAMETER SENSITIVITY\")\n",
        "    print(\"=\" * 80)\n",
        "    # Group A: Temporal overlap\n",
        "    to_results = [r2 for r2 in results if r2['aqe_k'] == AQE_K]\n",
        "    if to_results:\n",
        "        print(\"\\n--- Temporal Overlap Bonus ---\")\n",
        "        for r2 in sorted(to_results, key=lambda x: x['to_bonus']):\n",
        "            print(f\"  bonus={r2['to_bonus']:.2f} max_t={r2['to_max_time']:.1f} enabled={r2['to_enabled']} \"\n",
        "                  f\"-> mtmc_idf1={r2['mtmc_idf1']:.4f}\")\n",
        "    # Group B: AQE K\n",
        "    k_results = [r2 for r2 in results if r2['to_bonus'] == 0.05 and r2['to_max_time'] == 5.0 and r2['to_enabled']]\n",
        "    if k_results:\n",
        "        print(\"\\n--- AQE K ---\")\n",
        "        for r2 in sorted(k_results, key=lambda x: x['aqe_k']):\n",
        "            print(f\"  k={r2['aqe_k']} -> mtmc_idf1={r2['mtmc_idf1']:.4f}\")\n",
        "\n",
        "    # Save results\n",
        "    import json as _json\n",
        "    results_path = DATA_OUT / \"scan_results.json\"\n",
        "    with open(results_path, \"w\") as _f:\n",
        "        _json.dump({\"scan\": \"v75_consolidated\", \"results\": results}, _f, indent=2)\n",
        "    print(f\"\\nScan results saved to {results_path}\")\n",
        "    import shutil as _shutil\n",
        "    _out = Path(\"/kaggle/working\")\n",
        "    _shutil.copy2(str(results_path), str(_out / \"scan_results.json\"))\n",
        "    print(f\"Copied scan_results.json to {_out}\")\n",
        "else:\n",
        "    print(\"Scan disabled. Set SCAN_ENABLED = True to run grid search.\")\n",
    ]
    cell15["source"] = new_c15

    with open(NB, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=True)
    print("[OK] 10c notebook updated for v75")

    # Verify
    print("\n--- Cell 9 preview (first 10 lines) ---")
    for line in new_c9[:10]:
        print(f"  {line}", end="")
    print("\n--- Cell 12 key overrides ---")
    for line in new_c12:
        if "fic.regularisation" in line or "min_trajectory_frames" in line or "cross_id_nms_iou" in line:
            print(f"  {line}", end="")
    print("\n--- Cell 15 config count ---")
    print(f"  SCAN_ENABLED = True")
    print(f"  13 scan configs")


if __name__ == "__main__":
    update_notebook()
